// Source: https://fonts.google.com/metadata/fonts, snapshot taken 2026-06-04.
export const googleFontsCatalog = [
  { family: 'Roboto', category: 'Sans Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  { family: 'Open Sans', category: 'Sans Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  { family: 'Inter', category: 'Sans Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  { family: 'Montserrat', category: 'Sans Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  { family: 'Noto Sans', category: 'Sans Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  { family: 'Arimo', category: 'Sans Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  {
    family: 'Roboto Condensed',
    category: 'Sans Serif',
    subsets: ['cyrillic', 'latin'],
    variants: ['400', '700', '400i'],
  },
  { family: 'Oswald', category: 'Sans Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700'] },
  { family: 'Raleway', category: 'Sans Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  { family: 'Nunito Sans', category: 'Sans Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  { family: 'Rubik', category: 'Sans Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  { family: 'Ubuntu', category: 'Sans Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  { family: 'Manrope', category: 'Sans Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700'] },
  { family: 'PT Sans', category: 'Sans Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  { family: 'Mulish', category: 'Sans Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  { family: 'Source Sans 3', category: 'Sans Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  { family: 'IBM Plex Sans', category: 'Sans Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  { family: 'Fira Sans', category: 'Sans Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  { family: 'Jost', category: 'Sans Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  { family: 'Onest', category: 'Sans Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700'] },
  { family: 'Noto Serif', category: 'Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  { family: 'Playfair Display', category: 'Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  { family: 'Roboto Slab', category: 'Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700'] },
  { family: 'Merriweather', category: 'Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  { family: 'Lora', category: 'Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  { family: 'PT Serif', category: 'Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  { family: 'Cormorant Garamond', category: 'Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  { family: 'EB Garamond', category: 'Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  { family: 'Bitter', category: 'Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  { family: 'Source Serif 4', category: 'Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  { family: 'IBM Plex Serif', category: 'Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  { family: 'Literata', category: 'Serif', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  { family: 'Roboto Mono', category: 'Monospace', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  {
    family: 'Source Code Pro',
    category: 'Monospace',
    subsets: ['cyrillic', 'latin'],
    variants: ['400', '700', '400i'],
  },
  { family: 'JetBrains Mono', category: 'Monospace', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  { family: 'IBM Plex Mono', category: 'Monospace', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  { family: 'Geist Mono', category: 'Monospace', subsets: ['cyrillic', 'latin'], variants: ['400', '700', '400i'] },
  { family: 'Fira Code', category: 'Monospace', subsets: ['cyrillic', 'latin'], variants: ['400', '700'] },
  { family: 'Comfortaa', category: 'Display', subsets: ['cyrillic', 'latin'], variants: ['400', '700'] },
  { family: 'Lobster', category: 'Display', subsets: ['cyrillic', 'latin'], variants: ['400'] },
  { family: 'Forum', category: 'Display', subsets: ['cyrillic', 'latin'], variants: ['400'] },
  { family: 'Yeseva One', category: 'Display', subsets: ['cyrillic', 'latin'], variants: ['400'] },
  { family: 'Poiret One', category: 'Display', subsets: ['cyrillic', 'latin'], variants: ['400'] },
  { family: 'Tektur', category: 'Display', subsets: ['cyrillic', 'latin'], variants: ['400', '700'] },
  { family: 'Caveat', category: 'Handwriting', subsets: ['cyrillic', 'latin'], variants: ['400', '700'] },
  { family: 'Pacifico', category: 'Handwriting', subsets: ['cyrillic', 'latin'], variants: ['400'] },
  { family: 'Great Vibes', category: 'Handwriting', subsets: ['cyrillic', 'latin'], variants: ['400'] },
  { family: 'Amatic SC', category: 'Handwriting', subsets: ['cyrillic', 'latin'], variants: ['400', '700'] },
  { family: 'Bad Script', category: 'Handwriting', subsets: ['cyrillic', 'latin'], variants: ['400'] },
  { family: 'Pangolin', category: 'Handwriting', subsets: ['cyrillic', 'latin'], variants: ['400'] },
];
